name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory: web
      php: 7.4
      # php_extensions: 'calendar gd'
      composer: 2

    steps:
    - uses: actions/checkout@v2

    - name: Validate dependencies
      uses: php-actions/composer@v5
      with:
        php_version: ${{env.php}}
        version: ${{env.composer}}
        working_dir: ${{env.working-directory}}
        command: validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: ${{env.working-directory}}/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: ${{env.php}}
        version: ${{env.composer}}
        working_dir: ${{env.working-directory}}
        #php_extensions: ${{env.php_extensions}}
        args: --prefer-dist
        command: install

    - name: Test
      uses: php-actions/composer@v5
      with:
        php_version: ${{env.php}}
        version: ${{env.composer}}
        working_dir: ${{env.working-directory}}
        #php_extensions: ${{env.php_extensions}}
        command: test
